### ISSUE TITLE
Only from 0-100, not 100-0

### ISSUE THREAD

**Issue by derEnky** [indextwo/jquery-percentwithinviewport#1]
Hi,

is it possible to have something like this. Something 0% in View then it goes up to 100%.

After it reaches 100%, it's not going back to 0% while you scroll down.

Top of The Page Element = 0%
You Scroll down, Element = 50%
Your Scroll down Element = 100%
You passed the element, it stays at 100%.

**Comment by indextwo** [comment]
Sorry for the ultra-late reply. I never got a notification about this, so I only just saw it while tidying up my repos.

Not sure I understand. It already tracks the percentage of the elements within the viewport, going in either direction. If you scroll up or down, it tracks the percentage of the element within the viewport every time you make the call. 

For 'live' checking, it might depend on what you're using to monitor the window scroll, but I tested the demo out on FF, Chrome, Opera, Edge & Safari, and it works exactly as expected. Here's a quick video of it in Opera:

https://user-images.githubusercontent.com/1560590/107887929-81e74580-6f01-11eb-8b16-0b7f377cafc4.mp4
